// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AppCustomProductPageUpdateRequest: Codable {
	public var data: Data

	public struct Data: Codable {
		public var type: `Type`
		public var id: String
		public var attributes: Attributes?

		public enum `Type`: String, Codable, CaseIterable {
			case appCustomProductPages
		}

		public struct Attributes: Codable {
			public var name: String?
			public var isVisible: Bool?

			public init(name: String? = nil, isVisible: Bool? = nil) {
				self.name = name
				self.isVisible = isVisible
			}

			private enum CodingKeys: String, CodingKey {
				case name
				case isVisible = "visible"
			}
		}

		public init(type: `Type`, id: String, attributes: Attributes? = nil) {
			self.type = type
			self.id = id
			self.attributes = attributes
		}
	}

	public init(data: Data) {
		self.data = data
	}
}
