// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AppClipDefaultExperienceUpdateRequest: Codable {
	public var data: Data

	public struct Data: Codable {
		public var type: `Type`
		public var id: String
		public var attributes: Attributes?
		public var relationships: Relationships?

		public enum `Type`: String, Codable, CaseIterable {
			case appClipDefaultExperiences
		}

		public struct Attributes: Codable {
			public var action: AppClipAction?

			public init(action: AppClipAction? = nil) {
				self.action = action
			}
		}

		public struct Relationships: Codable {
			public var releaseWithAppStoreVersion: ReleaseWithAppStoreVersion?

			public struct ReleaseWithAppStoreVersion: Codable {
				public var data: Data?

				public struct Data: Codable {
					public var type: `Type`
					public var id: String

					public enum `Type`: String, Codable, CaseIterable {
						case appStoreVersions
					}

					public init(type: `Type`, id: String) {
						self.type = type
						self.id = id
					}
				}

				public init(data: Data? = nil) {
					self.data = data
				}
			}

			public init(releaseWithAppStoreVersion: ReleaseWithAppStoreVersion? = nil) {
				self.releaseWithAppStoreVersion = releaseWithAppStoreVersion
			}
		}

		public init(type: `Type`, id: String, attributes: Attributes? = nil, relationships: Relationships? = nil) {
			self.type = type
			self.id = id
			self.attributes = attributes
			self.relationships = relationships
		}
	}

	public init(data: Data) {
		self.data = data
	}
}
