// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AppEventLocalizationResponse: Codable {
	/// AppEventLocalization
	public var data: AppEventLocalization
	public var included: [IncludedItem]?
	public var links: DocumentLinks

	public enum IncludedItem: Codable {
		case appEvent(AppEvent)
		case appEventScreenshot(AppEventScreenshot)
		case appEventVideoClip(AppEventVideoClip)

		public init(from decoder: Decoder) throws {
			let container = try decoder.singleValueContainer()
			if let value = try? container.decode(AppEvent.self) {
				self = .appEvent(value)
			} else if let value = try? container.decode(AppEventScreenshot.self) {
				self = .appEventScreenshot(value)
			} else if let value = try? container.decode(AppEventVideoClip.self) {
				self = .appEventVideoClip(value)
			} else {
				throw DecodingError.dataCorruptedError(in: container, debugDescription: "Failed to intialize `oneOf`")
			}
		}

		public func encode(to encoder: Encoder) throws {
			var container = encoder.singleValueContainer()
			switch self {
			case .appEvent(let value): try container.encode(value)
			case .appEventScreenshot(let value): try container.encode(value)
			case .appEventVideoClip(let value): try container.encode(value)
			}
		}
	}

	public init(data: AppEventLocalization, included: [IncludedItem]? = nil, links: DocumentLinks) {
		self.data = data
		self.included = included
		self.links = links
	}

	public init(from decoder: Decoder) throws {
		let values = try decoder.container(keyedBy: StringCodingKey.self)
		self.data = try values.decode(AppEventLocalization.self, forKey: "data")
		self.included = try values.decodeIfPresent([IncludedItem].self, forKey: "included")
		self.links = try values.decode(DocumentLinks.self, forKey: "links")
	}

	public func encode(to encoder: Encoder) throws {
		var values = encoder.container(keyedBy: StringCodingKey.self)
		try values.encode(data, forKey: "data")
		try values.encodeIfPresent(included, forKey: "included")
		try values.encode(links, forKey: "links")
	}
}
