// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AppMediaStateError: Codable {
	public var code: String?
	public var description: String?

	public init(code: String? = nil, description: String? = nil) {
		self.code = code
		self.description = description
	}
}
