// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AppPriceTierResponse: Codable {
	/// AppPriceTier
	public var data: AppPriceTier
	public var included: [AppPricePoint]?
	public var links: DocumentLinks

	public init(data: AppPriceTier, included: [AppPricePoint]? = nil, links: DocumentLinks) {
		self.data = data
		self.included = included
		self.links = links
	}
}
