// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AppPriceTiersResponse: Codable {
	public var data: [AppPriceTier]
	public var included: [AppPricePoint]?
	public var links: PagedDocumentLinks
	public var meta: PagingInformation?

	public init(data: [AppPriceTier], included: [AppPricePoint]? = nil, links: PagedDocumentLinks, meta: PagingInformation? = nil) {
		self.data = data
		self.included = included
		self.links = links
		self.meta = meta
	}
}
