// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AppStoreVersionPhasedRelease: Codable {
	public var type: `Type`
	public var id: String
	public var attributes: Attributes?
	public var links: ResourceLinks

	public enum `Type`: String, Codable, CaseIterable {
		case appStoreVersionPhasedReleases
	}

	public struct Attributes: Codable {
		public var phasedReleaseState: PhasedReleaseState?
		public var startDate: Date?
		public var totalPauseDuration: Int?
		public var currentDayNumber: Int?

		public init(phasedReleaseState: PhasedReleaseState? = nil, startDate: Date? = nil, totalPauseDuration: Int? = nil, currentDayNumber: Int? = nil) {
			self.phasedReleaseState = phasedReleaseState
			self.startDate = startDate
			self.totalPauseDuration = totalPauseDuration
			self.currentDayNumber = currentDayNumber
		}
	}

	public init(type: `Type`, id: String, attributes: Attributes? = nil, links: ResourceLinks) {
		self.type = type
		self.id = id
		self.attributes = attributes
		self.links = links
	}
}
