// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct AppStoreVersionExperimentTreatmentLocalizationCreateRequest: Codable {
	public var data: Data

	public struct Data: Codable {
		public var type: `Type`
		public var attributes: Attributes
		public var relationships: Relationships

		public enum `Type`: String, Codable, CaseIterable {
			case appStoreVersionExperimentTreatmentLocalizations
		}

		public struct Attributes: Codable {
			public var locale: String

			public init(locale: String) {
				self.locale = locale
			}
		}

		public struct Relationships: Codable {
			public var appStoreVersionExperimentTreatment: AppStoreVersionExperimentTreatment

			public struct AppStoreVersionExperimentTreatment: Codable {
				public var data: Data

				public struct Data: Codable {
					public var type: `Type`
					public var id: String

					public enum `Type`: String, Codable, CaseIterable {
						case appStoreVersionExperimentTreatments
					}

					public init(type: `Type`, id: String) {
						self.type = type
						self.id = id
					}
				}

				public init(data: Data) {
					self.data = data
				}
			}

			public init(appStoreVersionExperimentTreatment: AppStoreVersionExperimentTreatment) {
				self.appStoreVersionExperimentTreatment = appStoreVersionExperimentTreatment
			}
		}

		public init(type: `Type`, attributes: Attributes, relationships: Relationships) {
			self.type = type
			self.attributes = attributes
			self.relationships = relationships
		}
	}

	public init(data: Data) {
		self.data = data
	}
}
