// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct BetaAppClipInvocationCreateRequest: Codable {
	public var data: Data
	public var included: [BetaAppClipInvocationLocalizationInlineCreate]?

	public struct Data: Codable {
		public var type: `Type`
		public var attributes: Attributes
		public var relationships: Relationships

		public enum `Type`: String, Codable, CaseIterable {
			case betaAppClipInvocations
		}

		public struct Attributes: Codable {
			public var url: URL

			public init(url: URL) {
				self.url = url
			}
		}

		public struct Relationships: Codable {
			public var buildBundle: BuildBundle
			public var betaAppClipInvocationLocalizations: BetaAppClipInvocationLocalizations

			public struct BuildBundle: Codable {
				public var data: Data

				public struct Data: Codable {
					public var type: `Type`
					public var id: String

					public enum `Type`: String, Codable, CaseIterable {
						case buildBundles
					}

					public init(type: `Type`, id: String) {
						self.type = type
						self.id = id
					}
				}

				public init(data: Data) {
					self.data = data
				}
			}

			public struct BetaAppClipInvocationLocalizations: Codable {
				public var data: [Datum]

				public struct Datum: Codable {
					public var type: `Type`
					public var id: String

					public enum `Type`: String, Codable, CaseIterable {
						case betaAppClipInvocationLocalizations
					}

					public init(type: `Type`, id: String) {
						self.type = type
						self.id = id
					}
				}

				public init(data: [Datum]) {
					self.data = data
				}
			}

			public init(buildBundle: BuildBundle, betaAppClipInvocationLocalizations: BetaAppClipInvocationLocalizations) {
				self.buildBundle = buildBundle
				self.betaAppClipInvocationLocalizations = betaAppClipInvocationLocalizations
			}
		}

		public init(type: `Type`, attributes: Attributes, relationships: Relationships) {
			self.type = type
			self.attributes = attributes
			self.relationships = relationships
		}
	}

	public init(data: Data, included: [BetaAppClipInvocationLocalizationInlineCreate]? = nil) {
		self.data = data
		self.included = included
	}
}
