// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct BetaLicenseAgreementsResponse: Codable {
	public var data: [BetaLicenseAgreement]
	public var included: [App]?
	public var links: PagedDocumentLinks
	public var meta: PagingInformation?

	public init(data: [BetaLicenseAgreement], included: [App]? = nil, links: PagedDocumentLinks, meta: PagingInformation? = nil) {
		self.data = data
		self.included = included
		self.links = links
		self.meta = meta
	}
}
