// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct BuildBetaDetailResponse: Codable {
	/// BuildBetaDetail
	public var data: BuildBetaDetail
	public var included: [Build]?
	public var links: DocumentLinks

	public init(data: BuildBetaDetail, included: [Build]? = nil, links: DocumentLinks) {
		self.data = data
		self.included = included
		self.links = links
	}
}
