// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct CertificateCreateRequest: Codable {
	public var data: Data

	public struct Data: Codable {
		public var type: `Type`
		public var attributes: Attributes

		public enum `Type`: String, Codable, CaseIterable {
			case certificates
		}

		public struct Attributes: Codable {
			public var csrContent: String
			public var certificateType: CertificateType

			public init(csrContent: String, certificateType: CertificateType) {
				self.csrContent = csrContent
				self.certificateType = certificateType
			}
		}

		public init(type: `Type`, attributes: Attributes) {
			self.type = type
			self.attributes = attributes
		}
	}

	public init(data: Data) {
		self.data = data
	}
}
