// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct CiArtifactsResponse: Codable {
	public var data: [CiArtifact]
	public var links: PagedDocumentLinks
	public var meta: PagingInformation?

	public init(data: [CiArtifact], links: PagedDocumentLinks, meta: PagingInformation? = nil) {
		self.data = data
		self.links = links
		self.meta = meta
	}
}
