// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct CiTestResultResponse: Codable {
	/// CiTestResult
	public var data: CiTestResult
	public var links: DocumentLinks

	public init(data: CiTestResult, links: DocumentLinks) {
		self.data = data
		self.links = links
	}
}
