// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct CustomerReviewsResponse: Codable {
	public var data: [CustomerReview]
	public var included: [CustomerReviewResponseV1]?
	public var links: PagedDocumentLinks
	public var meta: PagingInformation?

	public init(data: [CustomerReview], included: [CustomerReviewResponseV1]? = nil, links: PagedDocumentLinks, meta: PagingInformation? = nil) {
		self.data = data
		self.included = included
		self.links = links
		self.meta = meta
	}
}
