// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct DeviceResponse: Codable {
	/// Device
	public var data: Device
	public var links: DocumentLinks

	public init(data: Device, links: DocumentLinks) {
		self.data = data
		self.links = links
	}
}
