// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

/// JsonPointer
public struct ErrorSourcePointer: Codable {
	public var pointer: String?

	public init(pointer: String? = nil) {
		self.pointer = pointer
	}
}
