// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct InAppPurchaseLocalizationCreateRequest: Codable {
	public var data: Data

	public struct Data: Codable {
		public var type: `Type`
		public var attributes: Attributes
		public var relationships: Relationships

		public enum `Type`: String, Codable, CaseIterable {
			case inAppPurchaseLocalizations
		}

		public struct Attributes: Codable {
			public var name: String
			public var locale: String
			public var description: String?

			public init(name: String, locale: String, description: String? = nil) {
				self.name = name
				self.locale = locale
				self.description = description
			}
		}

		public struct Relationships: Codable {
			public var inAppPurchaseV2: InAppPurchaseV2

			public struct InAppPurchaseV2: Codable {
				public var data: Data

				public struct Data: Codable {
					public var type: `Type`
					public var id: String

					public enum `Type`: String, Codable, CaseIterable {
						case inAppPurchases
					}

					public init(type: `Type`, id: String) {
						self.type = type
						self.id = id
					}
				}

				public init(data: Data) {
					self.data = data
				}
			}

			public init(inAppPurchaseV2: InAppPurchaseV2) {
				self.inAppPurchaseV2 = inAppPurchaseV2
			}
		}

		public init(type: `Type`, attributes: Attributes, relationships: Relationships) {
			self.type = type
			self.attributes = attributes
			self.relationships = relationships
		}
	}

	public init(data: Data) {
		self.data = data
	}
}
