// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct InAppPurchasePriceInlineCreate: Codable {
	public var type: `Type`
	public var id: String?
	public var attributes: Attributes?
	public var relationships: Relationships?

	public enum `Type`: String, Codable, CaseIterable {
		case inAppPurchasePrices
	}

	public struct Attributes: Codable {
		public var startDate: String?

		public init(startDate: String? = nil) {
			self.startDate = startDate
		}
	}

	public struct Relationships: Codable {
		public var inAppPurchaseV2: InAppPurchaseV2?
		public var inAppPurchasePricePoint: InAppPurchasePricePoint?

		public struct InAppPurchaseV2: Codable {
			public var data: Data?

			public struct Data: Codable {
				public var type: `Type`
				public var id: String

				public enum `Type`: String, Codable, CaseIterable {
					case inAppPurchases
				}

				public init(type: `Type`, id: String) {
					self.type = type
					self.id = id
				}
			}

			public init(data: Data? = nil) {
				self.data = data
			}
		}

		public struct InAppPurchasePricePoint: Codable {
			public var data: Data?

			public struct Data: Codable {
				public var type: `Type`
				public var id: String

				public enum `Type`: String, Codable, CaseIterable {
					case inAppPurchasePricePoints
				}

				public init(type: `Type`, id: String) {
					self.type = type
					self.id = id
				}
			}

			public init(data: Data? = nil) {
				self.data = data
			}
		}

		public init(inAppPurchaseV2: InAppPurchaseV2? = nil, inAppPurchasePricePoint: InAppPurchasePricePoint? = nil) {
			self.inAppPurchaseV2 = inAppPurchaseV2
			self.inAppPurchasePricePoint = inAppPurchasePricePoint
		}
	}

	public init(type: `Type`, id: String? = nil, attributes: Attributes? = nil, relationships: Relationships? = nil) {
		self.type = type
		self.id = id
		self.attributes = attributes
		self.relationships = relationships
	}
}
