// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct PagingInformation: Codable {
	public var paging: Paging

	public struct Paging: Codable {
		public var total: Int?
		public var limit: Int

		public init(total: Int? = nil, limit: Int) {
			self.total = total
			self.limit = limit
		}
	}

	public init(paging: Paging) {
		self.paging = paging
	}
}
