// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct ScmGitReferencesResponse: Codable {
	public var data: [ScmGitReference]
	public var included: [ScmRepository]?
	public var links: PagedDocumentLinks
	public var meta: PagingInformation?

	public init(data: [ScmGitReference], included: [ScmRepository]? = nil, links: PagedDocumentLinks, meta: PagingInformation? = nil) {
		self.data = data
		self.included = included
		self.links = links
		self.meta = meta
	}
}
