// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct ScmPullRequestResponse: Codable {
	/// ScmPullRequest
	public var data: ScmPullRequest
	public var included: [ScmRepository]?
	public var links: DocumentLinks

	public init(data: ScmPullRequest, included: [ScmRepository]? = nil, links: DocumentLinks) {
		self.data = data
		self.included = included
		self.links = links
	}
}
