// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct SubscriptionGracePeriodUpdateRequest: Codable {
	public var data: Data
	public var included: [AppInlineCreate]?

	public struct Data: Codable {
		public var type: `Type`
		public var id: String
		public var attributes: Attributes?
		public var relationships: Relationships?

		public enum `Type`: String, Codable, CaseIterable {
			case subscriptionGracePeriods
		}

		public struct Attributes: Codable {
			public var isOptIn: Bool?

			public init(isOptIn: Bool? = nil) {
				self.isOptIn = isOptIn
			}

			private enum CodingKeys: String, CodingKey {
				case isOptIn = "optIn"
			}
		}

		public struct Relationships: Codable {
			public var app: App?

			public struct App: Codable {
				public var data: Data?

				public struct Data: Codable {
					public var type: `Type`
					public var id: String

					public enum `Type`: String, Codable, CaseIterable {
						case apps
					}

					public init(type: `Type`, id: String) {
						self.type = type
						self.id = id
					}
				}

				public init(data: Data? = nil) {
					self.data = data
				}
			}

			public init(app: App? = nil) {
				self.app = app
			}
		}

		public init(type: `Type`, id: String, attributes: Attributes? = nil, relationships: Relationships? = nil) {
			self.type = type
			self.id = id
			self.attributes = attributes
			self.relationships = relationships
		}
	}

	public init(data: Data, included: [AppInlineCreate]? = nil) {
		self.data = data
		self.included = included
	}
}
