// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct SubscriptionPricePointInlineCreate: Codable {
	public var type: `Type`
	public var id: String?

	public enum `Type`: String, Codable, CaseIterable {
		case subscriptionPricePoints
	}

	public init(type: `Type`, id: String? = nil) {
		self.type = type
		self.id = id
	}
}
