// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation

public struct UserInvitationResponse: Codable {
	/// UserInvitation
	public var data: UserInvitation
	public var included: [App]?
	public var links: DocumentLinks

	public init(data: UserInvitation, included: [App]? = nil, links: DocumentLinks) {
		self.data = data
		self.included = included
		self.links = links
	}
}
