// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.AppCategories {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/appCategories/{id}`
		public let path: String

		public func get(parameters: GetParameters? = nil) -> Request<AppStoreConnect_Swift_SDK.AppCategoryResponse> {
			.get(path, query: parameters?.asQuery)
		}

		public struct GetParameters {
			public var fieldsAppCategories: [FieldsAppCategories]?
			public var include: [Include]?
			public var limitSubcategories: Int?

			public enum FieldsAppCategories: String, Codable, CaseIterable {
				case parent
				case platforms
				case subcategories
			}

			public enum Include: String, Codable, CaseIterable {
				case parent
				case subcategories
			}

			public init(fieldsAppCategories: [FieldsAppCategories]? = nil, include: [Include]? = nil, limitSubcategories: Int? = nil) {
				self.fieldsAppCategories = fieldsAppCategories
				self.include = include
				self.limitSubcategories = limitSubcategories
			}

			public var asQuery: [(String, String?)] {
				let encoder = URLQueryEncoder(explode: false)
				encoder.encode(fieldsAppCategories, forKey: "fields[appCategories]")
				encoder.encode(include, forKey: "include")
				encoder.encode(limitSubcategories, forKey: "limit[subcategories]")
				return encoder.items
			}
		}
	}
}
