// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.AppScreenshots {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/appScreenshots/{id}`
		public let path: String

		public func get(fieldsAppScreenshots: [FieldsAppScreenshots]? = nil, include: [Include]? = nil) -> Request<AppStoreConnect_Swift_SDK.AppScreenshotResponse> {
			.get(path, query: makeGetQuery(fieldsAppScreenshots, include))
		}

		private func makeGetQuery(_ fieldsAppScreenshots: [FieldsAppScreenshots]?, _ include: [Include]?) -> [(String, String?)] {
			let encoder = URLQueryEncoder(explode: false)
			encoder.encode(fieldsAppScreenshots, forKey: "fields[appScreenshots]")
			encoder.encode(include, forKey: "include")
			return encoder.items
		}

		public enum FieldsAppScreenshots: String, Codable, CaseIterable {
			case appScreenshotSet
			case assetDeliveryState
			case assetToken
			case assetType
			case fileName
			case fileSize
			case imageAsset
			case sourceFileChecksum
			case uploadOperations
			case uploaded
		}

		public enum Include: String, Codable, CaseIterable {
			case appScreenshotSet
		}

		public func patch(_ body: AppStoreConnect_Swift_SDK.AppScreenshotUpdateRequest) -> Request<AppStoreConnect_Swift_SDK.AppScreenshotResponse> {
			.patch(path, body: body)
		}

		public var delete: Request<Void> {
			.delete(path)
		}
	}
}
