// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint {
	public static var appClipDefaultExperienceLocalizations: AppClipDefaultExperienceLocalizations {
		AppClipDefaultExperienceLocalizations(path: "/v1/appClipDefaultExperienceLocalizations")
	}

	public struct AppClipDefaultExperienceLocalizations {
		/// Path: `/v1/appClipDefaultExperienceLocalizations`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppClipDefaultExperienceLocalizationCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppClipDefaultExperienceLocalizationResponse> {
			.post(path, body: body)
		}
	}
}
