// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var betaTesterInvitations: BetaTesterInvitations {
		BetaTesterInvitations(path: "/v1/betaTesterInvitations")
	}

	public struct BetaTesterInvitations {
		/// Path: `/v1/betaTesterInvitations`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.BetaTesterInvitationCreateRequest) -> Request<AppStoreConnect_Swift_SDK.BetaTesterInvitationResponse> {
			.post(path, body: body)
		}
	}
}
