// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.Apps.WithID.Relationships {
	public var appClips: AppClips {
		AppClips(path: path + "/appClips")
	}

	public struct AppClips {
		/// Path: `/v1/apps/{id}/relationships/appClips`
		public let path: String
	}
}
