// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint {
	public static var ciWorkflows: CiWorkflows {
		CiWorkflows(path: "/v1/ciWorkflows")
	}

	public struct CiWorkflows {
		/// Path: `/v1/ciWorkflows`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.CiWorkflowCreateRequest) -> Request<AppStoreConnect_Swift_SDK.CiWorkflowResponse> {
			.post(path, body: body)
		}
	}
}
