// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.Builds.WithID.Relationships {
	public var appStoreVersion: AppStoreVersion {
		AppStoreVersion(path: path + "/appStoreVersion")
	}

	public struct AppStoreVersion {
		/// Path: `/v1/builds/{id}/relationships/appStoreVersion`
		public let path: String
	}
}
