// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.V1.AppStoreVersionSubmissions {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/appStoreVersionSubmissions/{id}`
		public let path: String

		@available(*, deprecated, message: "Deprecated")
		public var delete: Request<Void> {
			.delete(path)
		}
	}
}
