// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.CiWorkflows.WithID.Relationships {
	public var buildRuns: BuildRuns {
		BuildRuns(path: path + "/buildRuns")
	}

	public struct BuildRuns {
		/// Path: `/v1/ciWorkflows/{id}/relationships/buildRuns`
		public let path: String
	}
}
