// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint {
	public static var appClipAdvancedExperienceImages: AppClipAdvancedExperienceImages {
		AppClipAdvancedExperienceImages(path: "/v1/appClipAdvancedExperienceImages")
	}

	public struct AppClipAdvancedExperienceImages {
		/// Path: `/v1/appClipAdvancedExperienceImages`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppClipAdvancedExperienceImageCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppClipAdvancedExperienceImageResponse> {
			.post(path, body: body)
		}
	}
}
