// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var appEventScreenshots: AppEventScreenshots {
		AppEventScreenshots(path: "/v1/appEventScreenshots")
	}

	public struct AppEventScreenshots {
		/// Path: `/v1/appEventScreenshots`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppEventScreenshotCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppEventScreenshotResponse> {
			.post(path, body: body)
		}
	}
}
