// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var inAppPurchases: InAppPurchases {
		InAppPurchases(path: "/v1/inAppPurchases")
	}

	public struct InAppPurchases {
		/// Path: `/v1/inAppPurchases`
		public let path: String
	}
}
