// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var endUserLicenseAgreements: EndUserLicenseAgreements {
		EndUserLicenseAgreements(path: "/v1/endUserLicenseAgreements")
	}

	public struct EndUserLicenseAgreements {
		/// Path: `/v1/endUserLicenseAgreements`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.EndUserLicenseAgreementCreateRequest) -> Request<AppStoreConnect_Swift_SDK.EndUserLicenseAgreementResponse> {
			.post(path, body: body)
		}
	}
}
