// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.Certificates {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/certificates/{id}`
		public let path: String

		public func get(fieldsCertificates: [FieldsCertificates]? = nil) -> Request<AppStoreConnect_Swift_SDK.CertificateResponse> {
			.get(path, query: makeGetQuery(fieldsCertificates))
		}

		private func makeGetQuery(_ fieldsCertificates: [FieldsCertificates]?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(fieldsCertificates, forKey: "fields[certificates]", explode: false)
			return encoder.items
		}

		public enum FieldsCertificates: String, Codable, CaseIterable {
			case certificateContent
			case certificateType
			case csrContent
			case displayName
			case expirationDate
			case name
			case platform
			case serialNumber
		}

		public var delete: Request<Void> {
			.delete(path)
		}
	}
}
