// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.AppCustomProductPages.WithID.Relationships {
	public var appCustomProductPageVersions: AppCustomProductPageVersions {
		AppCustomProductPageVersions(path: path + "/appCustomProductPageVersions")
	}

	public struct AppCustomProductPageVersions {
		/// Path: `/v1/appCustomProductPages/{id}/relationships/appCustomProductPageVersions`
		public let path: String
	}
}
