// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint {
	public static var appStoreVersionSubmissions: AppStoreVersionSubmissions {
		AppStoreVersionSubmissions(path: "/v1/appStoreVersionSubmissions")
	}

	public struct AppStoreVersionSubmissions {
		/// Path: `/v1/appStoreVersionSubmissions`
		public let path: String

		@available(*, deprecated, message: "Deprecated")
		public func post(_ body: AppStoreConnect_Swift_SDK.AppStoreVersionSubmissionCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppStoreVersionSubmissionResponse> {
			.post(path, body: body)
		}
	}
}
