// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.V1.InAppPurchaseLocalizations {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/inAppPurchaseLocalizations/{id}`
		public let path: String

		public func get(fieldsInAppPurchaseLocalizations: [FieldsInAppPurchaseLocalizations]? = nil, include: [Include]? = nil) -> Request<AppStoreConnect_Swift_SDK.InAppPurchaseLocalizationResponse> {
			.get(path, query: makeGetQuery(fieldsInAppPurchaseLocalizations, include))
		}

		private func makeGetQuery(_ fieldsInAppPurchaseLocalizations: [FieldsInAppPurchaseLocalizations]?, _ include: [Include]?) -> [(String, String?)] {
			let encoder = URLQueryEncoder(explode: false)
			encoder.encode(fieldsInAppPurchaseLocalizations, forKey: "fields[inAppPurchaseLocalizations]")
			encoder.encode(include, forKey: "include")
			return encoder.items
		}

		public enum FieldsInAppPurchaseLocalizations: String, Codable, CaseIterable {
			case description
			case inAppPurchaseV2
			case locale
			case name
			case state
		}

		public enum Include: String, Codable, CaseIterable {
			case inAppPurchaseV2
		}

		public func patch(_ body: AppStoreConnect_Swift_SDK.InAppPurchaseLocalizationUpdateRequest) -> Request<AppStoreConnect_Swift_SDK.InAppPurchaseLocalizationResponse> {
			.patch(path, body: body)
		}

		public var delete: Request<Void> {
			.delete(path)
		}
	}
}
