// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.V1.BundleIDs.WithID.Relationships {
	public var app: App {
		App(path: path + "/app")
	}

	public struct App {
		/// Path: `/v1/bundleIds/{id}/relationships/app`
		public let path: String
	}
}
