// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint {
	public static var appEventLocalizations: AppEventLocalizations {
		AppEventLocalizations(path: "/v1/appEventLocalizations")
	}

	public struct AppEventLocalizations {
		/// Path: `/v1/appEventLocalizations`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppEventLocalizationCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppEventLocalizationResponse> {
			.post(path, body: body)
		}
	}
}
