// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.CiBuildActions.WithID.Relationships {
	public var issues: Issues {
		Issues(path: path + "/issues")
	}

	public struct Issues {
		/// Path: `/v1/ciBuildActions/{id}/relationships/issues`
		public let path: String
	}
}
