// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var idfaDeclarations: IdfaDeclarations {
		IdfaDeclarations(path: "/v1/idfaDeclarations")
	}

	public struct IdfaDeclarations {
		/// Path: `/v1/idfaDeclarations`
		public let path: String

		@available(*, deprecated, message: "Deprecated")
		public func post(_ body: AppStoreConnect_Swift_SDK.IdfaDeclarationCreateRequest) -> Request<AppStoreConnect_Swift_SDK.IdfaDeclarationResponse> {
			.post(path, body: body)
		}
	}
}
