// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.CiProducts.WithID.Relationships {
	public var app: App {
		App(path: path + "/app")
	}

	public struct App {
		/// Path: `/v1/ciProducts/{id}/relationships/app`
		public let path: String
	}
}
