// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.CiBuildActions.WithID.Relationships {
	public var testResults: TestResults {
		TestResults(path: path + "/testResults")
	}

	public struct TestResults {
		/// Path: `/v1/ciBuildActions/{id}/relationships/testResults`
		public let path: String
	}
}
