// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.V1 {
	public var subscriptionOfferCodeOneTimeUseCodes: SubscriptionOfferCodeOneTimeUseCodes {
		SubscriptionOfferCodeOneTimeUseCodes(path: path + "/subscriptionOfferCodeOneTimeUseCodes")
	}

	public struct SubscriptionOfferCodeOneTimeUseCodes {
		/// Path: `/v1/subscriptionOfferCodeOneTimeUseCodes`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.SubscriptionOfferCodeOneTimeUseCodeCreateRequest) -> Request<AppStoreConnect_Swift_SDK.SubscriptionOfferCodeOneTimeUseCodeResponse> {
			.post(path, body: body)
		}
	}
}
