// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var appEvents: AppEvents {
		AppEvents(path: "/v1/appEvents")
	}

	public struct AppEvents {
		/// Path: `/v1/appEvents`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppEventCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppEventResponse> {
			.post(path, body: body)
		}
	}
}
