// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint.AppPreviews {
	public func id(_ id: String) -> WithID {
		WithID(path: "\(path)/\(id)")
	}

	public struct WithID {
		/// Path: `/v1/appPreviews/{id}`
		public let path: String

		public func get(fieldsAppPreviews: [FieldsAppPreviews]? = nil, include: [Include]? = nil) -> Request<AppStoreConnect_Swift_SDK.AppPreviewResponse> {
			.get(path, query: makeGetQuery(fieldsAppPreviews, include))
		}

		private func makeGetQuery(_ fieldsAppPreviews: [FieldsAppPreviews]?, _ include: [Include]?) -> [(String, String?)] {
			let encoder = URLQueryEncoder(explode: false)
			encoder.encode(fieldsAppPreviews, forKey: "fields[appPreviews]")
			encoder.encode(include, forKey: "include")
			return encoder.items
		}

		public enum FieldsAppPreviews: String, Codable, CaseIterable {
			case appPreviewSet
			case assetDeliveryState
			case fileName
			case fileSize
			case mimeType
			case previewFrameTimeCode
			case previewImage
			case sourceFileChecksum
			case uploadOperations
			case uploaded
			case videoURL = "videoUrl"
		}

		public enum Include: String, Codable, CaseIterable {
			case appPreviewSet
		}

		public func patch(_ body: AppStoreConnect_Swift_SDK.AppPreviewUpdateRequest) -> Request<AppStoreConnect_Swift_SDK.AppPreviewResponse> {
			.patch(path, body: body)
		}

		public var delete: Request<Void> {
			.delete(path)
		}
	}
}
