// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var appPreviewSets: AppPreviewSets {
		AppPreviewSets(path: "/v1/appPreviewSets")
	}

	public struct AppPreviewSets {
		/// Path: `/v1/appPreviewSets`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppPreviewSetCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppPreviewSetResponse> {
			.post(path, body: body)
		}
	}
}
