// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint {
	public static var appClipAppStoreReviewDetails: AppClipAppStoreReviewDetails {
		AppClipAppStoreReviewDetails(path: "/v1/appClipAppStoreReviewDetails")
	}

	public struct AppClipAppStoreReviewDetails {
		/// Path: `/v1/appClipAppStoreReviewDetails`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppClipAppStoreReviewDetailCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppClipAppStoreReviewDetailResponse> {
			.post(path, body: body)
		}
	}
}
