// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var gameCenterEnabledVersions: GameCenterEnabledVersions {
		GameCenterEnabledVersions(path: "/v1/gameCenterEnabledVersions")
	}

	public struct GameCenterEnabledVersions {
		/// Path: `/v1/gameCenterEnabledVersions`
		public let path: String
	}
}
