// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var scmPullRequests: ScmPullRequests {
		ScmPullRequests(path: "/v1/scmPullRequests")
	}

	public struct ScmPullRequests {
		/// Path: `/v1/scmPullRequests`
		public let path: String
	}
}
