// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.Users.WithID.Relationships {
	public var visibleApps: VisibleApps {
		VisibleApps(path: path + "/visibleApps")
	}

	public struct VisibleApps {
		/// Path: `/v1/users/{id}/relationships/visibleApps`
		public let path: String

		public func get(limit: Int? = nil) -> Request<AppStoreConnect_Swift_SDK.UserVisibleAppsLinkagesResponse> {
			.get(path, query: makeGetQuery(limit))
		}

		private func makeGetQuery(_ limit: Int?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(limit, forKey: "limit")
			return encoder.items
		}

		public func post(_ body: AppStoreConnect_Swift_SDK.UserVisibleAppsLinkagesRequest) -> Request<Void> {
			.post(path, body: body)
		}

		public func patch(_ body: AppStoreConnect_Swift_SDK.UserVisibleAppsLinkagesRequest) -> Request<Void> {
			.patch(path, body: body)
		}

		public func delete(_ body: AppStoreConnect_Swift_SDK.UserVisibleAppsLinkagesRequest) -> Request<Void> {
			.delete(path, body: body)
		}
	}
}
