// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.AppStoreVersions.WithID.Relationships {
	public var idfaDeclaration: IdfaDeclaration {
		IdfaDeclaration(path: path + "/idfaDeclaration")
	}

	public struct IdfaDeclaration {
		/// Path: `/v1/appStoreVersions/{id}/relationships/idfaDeclaration`
		public let path: String
	}
}
