// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint {
	public static var appInfoLocalizations: AppInfoLocalizations {
		AppInfoLocalizations(path: "/v1/appInfoLocalizations")
	}

	public struct AppInfoLocalizations {
		/// Path: `/v1/appInfoLocalizations`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppInfoLocalizationCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppInfoLocalizationResponse> {
			.post(path, body: body)
		}
	}
}
