// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint {
	public static var appStoreVersionReleaseRequests: AppStoreVersionReleaseRequests {
		AppStoreVersionReleaseRequests(path: "/v1/appStoreVersionReleaseRequests")
	}

	public struct AppStoreVersionReleaseRequests {
		/// Path: `/v1/appStoreVersionReleaseRequests`
		public let path: String

		public func post(_ body: AppStoreConnect_Swift_SDK.AppStoreVersionReleaseRequestCreateRequest) -> Request<AppStoreConnect_Swift_SDK.AppStoreVersionReleaseRequestResponse> {
			.post(path, body: body)
		}
	}
}
