// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import Get
import URLQueryEncoder

extension APIEndpoint {
	public static var diagnosticSignatures: DiagnosticSignatures {
		DiagnosticSignatures(path: "/v1/diagnosticSignatures")
	}

	public struct DiagnosticSignatures {
		/// Path: `/v1/diagnosticSignatures`
		public let path: String
	}
}
