// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.BetaTesters.WithID.Relationships {
	public var builds: Builds {
		Builds(path: path + "/builds")
	}

	public struct Builds {
		/// Path: `/v1/betaTesters/{id}/relationships/builds`
		public let path: String

		public func get(limit: Int? = nil) -> Request<AppStoreConnect_Swift_SDK.BetaTesterBuildsLinkagesResponse> {
			.get(path, query: makeGetQuery(limit))
		}

		private func makeGetQuery(_ limit: Int?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(limit, forKey: "limit")
			return encoder.items
		}

		public func post(_ body: AppStoreConnect_Swift_SDK.BetaTesterBuildsLinkagesRequest) -> Request<Void> {
			.post(path, body: body)
		}

		public func delete(_ body: AppStoreConnect_Swift_SDK.BetaTesterBuildsLinkagesRequest) -> Request<Void> {
			.delete(path, body: body)
		}
	}
}
