// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// swiftlint:disable all

import Foundation
import URLQueryEncoder

extension APIEndpoint.V1.AppStoreVersions.WithID {
	public var idfaDeclaration: IdfaDeclaration {
		IdfaDeclaration(path: path + "/idfaDeclaration")
	}

	public struct IdfaDeclaration {
		/// Path: `/v1/appStoreVersions/{id}/idfaDeclaration`
		public let path: String

		@available(*, deprecated, message: "Deprecated")
		public func get(fieldsIdfaDeclarations: [FieldsIdfaDeclarations]? = nil) -> Request<AppStoreConnect_Swift_SDK.IdfaDeclarationResponse> {
			.get(path, query: makeGetQuery(fieldsIdfaDeclarations))
		}

		private func makeGetQuery(_ fieldsIdfaDeclarations: [FieldsIdfaDeclarations]?) -> [(String, String?)] {
			let encoder = URLQueryEncoder()
			encoder.encode(fieldsIdfaDeclarations, forKey: "fields[idfaDeclarations]", explode: false)
			return encoder.items
		}

		public enum FieldsIdfaDeclarations: String, Codable, CaseIterable {
			case appStoreVersion
			case attributesActionWithPreviousAd
			case attributesAppInstallationToPreviousAd
			case honorsLimitedAdTracking
			case servesAds
		}
	}
}
